# version: "3.8"

# services:
#   ai:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: ai-app
#     container_name: ai-app
#     restart: always
#     ports: 
#       - "6000:6000"
#     volumes:
#       - ./model_cache:/app/models
#       - ./logs:/app/logs
#       - ./.env:/app/.env
#     environment:
#       # 기존 PostgreSQL 서버에 연결
#       DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${EC2_1_IP}:5432/${POSTGRES_DB}
#       OPENAI_API_KEY: ${OPENAI_API_KEY}
#       INTERNAL_AI_URL: ${INTERNAL_AI_URL}
#       HF_CACHE_DIR: /app/models
#       # 시간대 설정 추가 (KST 적용)
#       TZ: Asia/Seoul
#     networks:
#       - givu_ai-network
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:6000/health"]
#       interval: 30s
#       timeout: 10s
#       retries: 3

# networks:
#   givu_ai-network:
#     name: givu_ai-network
#     external: true